services:
  mongo:
    container_name: mongo
    image: mongo:latest
    volumes:
      - v-mongo:/data/db

  redis:
    container_name: redis
    image: redis:latest
    volumes:
      - v-redis:/data

  nginx:
    container_name: nginx
    build:
      context: nginx
      dockerfile: Dockerfile.dev
    depends_on:
      - api
      - client
    restart: always
    ports:
      - "8080:80"

  api:
    container_name: api
    build:
      context: server
      dockerfile: Dockerfile.dev
    volumes:
      - ./server/src:/server/src:ro
    depends_on:
      - mongo
      - redis
    environment:
      - CHOKIDAR_USEPOLLING=true
      - MONGO_URI=mongodb://mongo:27017
      - REDIS_URI=redis://redis:6379

  client:
    container_name: client
    build:
      context: client
      dockerfile: Dockerfile.dev
    volumes:
      - ./client/src:/app/src:ro
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  v-mongo: {}
  v-redis: {}
