services:
  redis:
    image: redis:latest
    volumes:
      - v-redis:/data

  api:
    build:
      context: server
      dockerfile: Dockerfile.prod
    environment:
      - MONGO_URI=${MONGO_URI}
    deploy:
      replicas: 3

  nginx:
    build:
      context: client
      dockerfile: Dockerfile.prod
    depends_on:
      - api
    restart: always
    ports:
      - "80:80"

volumes:
  v-redis: {}
